### ISSUE TITLE
[BUG] Getting urllib.error.HTTPError: HTTP Error 403: Forbidden with example project

### ISSUE THREAD

**Issue by alejamt00** [Owen-Cochell/cursepy#8] opened 2022-06-09 12:47 UTC
Hello, sorry for the inconvenience,  i am pretty new to this but I downloaded the api and tried the example project: 
```python
from cursepy import CurseClient  # Import the CurseClient

GAME_ID = 432  # ID of the game you want to fetch, in this case Minecraft

# Create the CurseClient:

curse = CurseClient()

# Get the game info:

game = curse.game(GAME_ID)

# Print the name of the game:

print(game.name)
```

but i only get this forbidden exception :(

```
PS C:\Users\Osaki\Documents\VS projects\cursePY> & C:/Users/Osaki/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Osaki/Documents/VS projects/cursePY/getData.py"
Traceback (most recent call last):
  File "c:\Users\Osaki\Documents\VS projects\cursePY\getData.py", line 11, in <module>
    game = curse.game(GAME_ID)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\wrapper.py", line 69, in game
    return self.handle(1, id)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\handlers\base.py", line 987, in handle
    inst = hand.handle(*args, **kwargs)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\handlers\base.py", line 408, in handle
    return super().handle()
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\handlers\base.py", line 182, in handle
    data_bytes = self.proto_call(*args, **kwargs)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\handlers\base.py", line 373, in proto_call
    return self.proto.get_data(self.url)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\proto.py", line 220, in get_data
    req = self.low_get(url, timeout=timeout)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\site-packages\cursepy\proto.py", line 260, in low_get
    self.last = urlopen(req, timeout=timeout if not None else self.timeout)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Osaki\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I really don't know if I am doing something wrong or just CurseForge blocked the access to the website so we cant use this tool anymore, or what happens :((

Sorry once more but i'm pretty noob hehe

**Comment by OwenCochell** [comment] 2022-06-09 17:55
Yeah no worries, the issue is on our end not yours!

Unfortunately curseforge has shut down the API we were using. This means that any requests will result in a forbidden error.  Myself and a few others are looking into some alternatives. Curseforge is releasing a new API for 3rd party developers, but it requires an API key to use, and may not be as complete as the old one.

Once we figure out an alternative, it will be pretty simple to update cursepy to use this new API. All I have to say right now is keep an eye out for any updates here, hopefully we will have a solution soon

Sorry about this inconvenience, hopefully we will have something soon!

**Comment by alejamt00** [comment] 2022-06-09 18:54
Ohhh i see, ok no problem, you guys are the best :) I'll wait patiently, i wish you the best and I hope this problem don't give you guys too many headaches haha. Good luck :)

**Comment by Advik-B** [comment] 2022-07-22 03:10
> 

Yea, same. I dont mind using an API key

**Comment by KorewaLidesu** [comment] 2022-07-24 04:31
Just interesting in non-API method
Link: https://curse.tools/

**Comment by OwenCochell** [comment] 2022-08-19 19:19
Apologies for the massive delay, but support for the official CurseForge API has just been implemented.

You will need an API key to interact with the service. I will also be looking at the curse.tools service, as I think implementing support for it could be useful!

Thanks, and sorry again for the delay. If this solves your problem then we can close this issue.

**Closed as completed** 2022-12-01 17:37 UTC
